'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''


def fibbo(limit):
    fibbo_list = [0, 1];
    while fibbo_list[-1] + fibbo_list[-2] < limit:
        fibbo_list.append(fibbo_list[-1] + fibbo_list[-2])
    return fibbo_list


print(sum(list(filter(lambda x: x % 2 == 0, fibbo(4000000)))))
